/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EpisodeIdRouteImport } from './routes/episode.$id'
import { Route as ApiAgentEpisodesRouteImport } from './routes/api/agent/episodes'
import { Route as ApiAgentConfigRouteImport } from './routes/api/agent/config'
import { Route as ApiAgentEpisodesIdRouteImport } from './routes/api/agent/episodes.$id'

const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodeIdRoute = EpisodeIdRouteImport.update({
  id: '/episode/$id',
  path: '/episode/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentEpisodesRoute = ApiAgentEpisodesRouteImport.update({
  id: '/api/agent/episodes',
  path: '/api/agent/episodes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentConfigRoute = ApiAgentConfigRouteImport.update({
  id: '/api/agent/config',
  path: '/api/agent/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentEpisodesIdRoute = ApiAgentEpisodesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAgentEpisodesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/library': typeof LibraryRoute
  '/episode/$id': typeof EpisodeIdRoute
  '/api/agent/config': typeof ApiAgentConfigRoute
  '/api/agent/episodes': typeof ApiAgentEpisodesRouteWithChildren
  '/api/agent/episodes/$id': typeof ApiAgentEpisodesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/library': typeof LibraryRoute
  '/episode/$id': typeof EpisodeIdRoute
  '/api/agent/config': typeof ApiAgentConfigRoute
  '/api/agent/episodes': typeof ApiAgentEpisodesRouteWithChildren
  '/api/agent/episodes/$id': typeof ApiAgentEpisodesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/library': typeof LibraryRoute
  '/episode/$id': typeof EpisodeIdRoute
  '/api/agent/config': typeof ApiAgentConfigRoute
  '/api/agent/episodes': typeof ApiAgentEpisodesRouteWithChildren
  '/api/agent/episodes/$id': typeof ApiAgentEpisodesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/library'
    | '/episode/$id'
    | '/api/agent/config'
    | '/api/agent/episodes'
    | '/api/agent/episodes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/library'
    | '/episode/$id'
    | '/api/agent/config'
    | '/api/agent/episodes'
    | '/api/agent/episodes/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/library'
    | '/episode/$id'
    | '/api/agent/config'
    | '/api/agent/episodes'
    | '/api/agent/episodes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LibraryRoute: typeof LibraryRoute
  EpisodeIdRoute: typeof EpisodeIdRoute
  ApiAgentConfigRoute: typeof ApiAgentConfigRoute
  ApiAgentEpisodesRoute: typeof ApiAgentEpisodesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episode/$id': {
      id: '/episode/$id'
      path: '/episode/$id'
      fullPath: '/episode/$id'
      preLoaderRoute: typeof EpisodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/episodes': {
      id: '/api/agent/episodes'
      path: '/api/agent/episodes'
      fullPath: '/api/agent/episodes'
      preLoaderRoute: typeof ApiAgentEpisodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/config': {
      id: '/api/agent/config'
      path: '/api/agent/config'
      fullPath: '/api/agent/config'
      preLoaderRoute: typeof ApiAgentConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/episodes/$id': {
      id: '/api/agent/episodes/$id'
      path: '/$id'
      fullPath: '/api/agent/episodes/$id'
      preLoaderRoute: typeof ApiAgentEpisodesIdRouteImport
      parentRoute: typeof ApiAgentEpisodesRoute
    }
  }
}

interface ApiAgentEpisodesRouteChildren {
  ApiAgentEpisodesIdRoute: typeof ApiAgentEpisodesIdRoute
}

const ApiAgentEpisodesRouteChildren: ApiAgentEpisodesRouteChildren = {
  ApiAgentEpisodesIdRoute: ApiAgentEpisodesIdRoute,
}

const ApiAgentEpisodesRouteWithChildren =
  ApiAgentEpisodesRoute._addFileChildren(ApiAgentEpisodesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LibraryRoute: LibraryRoute,
  EpisodeIdRoute: EpisodeIdRoute,
  ApiAgentConfigRoute: ApiAgentConfigRoute,
  ApiAgentEpisodesRoute: ApiAgentEpisodesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
