/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SelfImprovementRouteImport } from './routes/self-improvement'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as HowToMakeEducationalCartoonsRouteImport } from './routes/how-to-make-educational-cartoons'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EpisodeIdRouteImport } from './routes/episode.$id'
import { Route as ApiPublicAgentWebhookRouteImport } from './routes/api/public/agent-webhook'
import { Route as ApiAgentEpisodesRouteImport } from './routes/api/agent/episodes'
import { Route as ApiAgentConfigRouteImport } from './routes/api/agent/config'
import { Route as ApiAgentPromptsHistoryRouteImport } from './routes/api/agent/prompts/history'
import { Route as ApiAgentEpisodesIdRouteImport } from './routes/api/agent/episodes.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfImprovementRoute = SelfImprovementRouteImport.update({
  id: '/self-improvement',
  path: '/self-improvement',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToMakeEducationalCartoonsRoute =
  HowToMakeEducationalCartoonsRouteImport.update({
    id: '/how-to-make-educational-cartoons',
    path: '/how-to-make-educational-cartoons',
    getParentRoute: () => rootRouteImport,
  } as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodeIdRoute = EpisodeIdRouteImport.update({
  id: '/episode/$id',
  path: '/episode/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentWebhookRoute = ApiPublicAgentWebhookRouteImport.update({
  id: '/api/public/agent-webhook',
  path: '/api/public/agent-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentEpisodesRoute = ApiAgentEpisodesRouteImport.update({
  id: '/api/agent/episodes',
  path: '/api/agent/episodes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentConfigRoute = ApiAgentConfigRouteImport.update({
  id: '/api/agent/config',
  path: '/api/agent/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentPromptsHistoryRoute = ApiAgentPromptsHistoryRouteImport.update({
  id: '/api/agent/prompts/history',
  path: '/api/agent/prompts/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentEpisodesIdRoute = ApiAgentEpisodesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAgentEpisodesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/how-to-make-educational-cartoons': typeof HowToMakeEducationalCartoonsRoute
  '/library': typeof LibraryRoute
  '/self-improvement': typeof SelfImprovementRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/episode/$id': typeof EpisodeIdRoute
  '/api/agent/config': typeof ApiAgentConfigRoute
  '/api/agent/episodes': typeof ApiAgentEpisodesRouteWithChildren
  '/api/public/agent-webhook': typeof ApiPublicAgentWebhookRoute
  '/api/agent/episodes/$id': typeof ApiAgentEpisodesIdRoute
  '/api/agent/prompts/history': typeof ApiAgentPromptsHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/how-to-make-educational-cartoons': typeof HowToMakeEducationalCartoonsRoute
  '/library': typeof LibraryRoute
  '/self-improvement': typeof SelfImprovementRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/episode/$id': typeof EpisodeIdRoute
  '/api/agent/config': typeof ApiAgentConfigRoute
  '/api/agent/episodes': typeof ApiAgentEpisodesRouteWithChildren
  '/api/public/agent-webhook': typeof ApiPublicAgentWebhookRoute
  '/api/agent/episodes/$id': typeof ApiAgentEpisodesIdRoute
  '/api/agent/prompts/history': typeof ApiAgentPromptsHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/how-to-make-educational-cartoons': typeof HowToMakeEducationalCartoonsRoute
  '/library': typeof LibraryRoute
  '/self-improvement': typeof SelfImprovementRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/episode/$id': typeof EpisodeIdRoute
  '/api/agent/config': typeof ApiAgentConfigRoute
  '/api/agent/episodes': typeof ApiAgentEpisodesRouteWithChildren
  '/api/public/agent-webhook': typeof ApiPublicAgentWebhookRoute
  '/api/agent/episodes/$id': typeof ApiAgentEpisodesIdRoute
  '/api/agent/prompts/history': typeof ApiAgentPromptsHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/how-to-make-educational-cartoons'
    | '/library'
    | '/self-improvement'
    | '/sitemap.xml'
    | '/episode/$id'
    | '/api/agent/config'
    | '/api/agent/episodes'
    | '/api/public/agent-webhook'
    | '/api/agent/episodes/$id'
    | '/api/agent/prompts/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/how-to-make-educational-cartoons'
    | '/library'
    | '/self-improvement'
    | '/sitemap.xml'
    | '/episode/$id'
    | '/api/agent/config'
    | '/api/agent/episodes'
    | '/api/public/agent-webhook'
    | '/api/agent/episodes/$id'
    | '/api/agent/prompts/history'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/how-to-make-educational-cartoons'
    | '/library'
    | '/self-improvement'
    | '/sitemap.xml'
    | '/episode/$id'
    | '/api/agent/config'
    | '/api/agent/episodes'
    | '/api/public/agent-webhook'
    | '/api/agent/episodes/$id'
    | '/api/agent/prompts/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HowToMakeEducationalCartoonsRoute: typeof HowToMakeEducationalCartoonsRoute
  LibraryRoute: typeof LibraryRoute
  SelfImprovementRoute: typeof SelfImprovementRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  EpisodeIdRoute: typeof EpisodeIdRoute
  ApiAgentConfigRoute: typeof ApiAgentConfigRoute
  ApiAgentEpisodesRoute: typeof ApiAgentEpisodesRouteWithChildren
  ApiPublicAgentWebhookRoute: typeof ApiPublicAgentWebhookRoute
  ApiAgentPromptsHistoryRoute: typeof ApiAgentPromptsHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-improvement': {
      id: '/self-improvement'
      path: '/self-improvement'
      fullPath: '/self-improvement'
      preLoaderRoute: typeof SelfImprovementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-make-educational-cartoons': {
      id: '/how-to-make-educational-cartoons'
      path: '/how-to-make-educational-cartoons'
      fullPath: '/how-to-make-educational-cartoons'
      preLoaderRoute: typeof HowToMakeEducationalCartoonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episode/$id': {
      id: '/episode/$id'
      path: '/episode/$id'
      fullPath: '/episode/$id'
      preLoaderRoute: typeof EpisodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-webhook': {
      id: '/api/public/agent-webhook'
      path: '/api/public/agent-webhook'
      fullPath: '/api/public/agent-webhook'
      preLoaderRoute: typeof ApiPublicAgentWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/episodes': {
      id: '/api/agent/episodes'
      path: '/api/agent/episodes'
      fullPath: '/api/agent/episodes'
      preLoaderRoute: typeof ApiAgentEpisodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/config': {
      id: '/api/agent/config'
      path: '/api/agent/config'
      fullPath: '/api/agent/config'
      preLoaderRoute: typeof ApiAgentConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/prompts/history': {
      id: '/api/agent/prompts/history'
      path: '/api/agent/prompts/history'
      fullPath: '/api/agent/prompts/history'
      preLoaderRoute: typeof ApiAgentPromptsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/episodes/$id': {
      id: '/api/agent/episodes/$id'
      path: '/$id'
      fullPath: '/api/agent/episodes/$id'
      preLoaderRoute: typeof ApiAgentEpisodesIdRouteImport
      parentRoute: typeof ApiAgentEpisodesRoute
    }
  }
}

interface ApiAgentEpisodesRouteChildren {
  ApiAgentEpisodesIdRoute: typeof ApiAgentEpisodesIdRoute
}

const ApiAgentEpisodesRouteChildren: ApiAgentEpisodesRouteChildren = {
  ApiAgentEpisodesIdRoute: ApiAgentEpisodesIdRoute,
}

const ApiAgentEpisodesRouteWithChildren =
  ApiAgentEpisodesRoute._addFileChildren(ApiAgentEpisodesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HowToMakeEducationalCartoonsRoute: HowToMakeEducationalCartoonsRoute,
  LibraryRoute: LibraryRoute,
  SelfImprovementRoute: SelfImprovementRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  EpisodeIdRoute: EpisodeIdRoute,
  ApiAgentConfigRoute: ApiAgentConfigRoute,
  ApiAgentEpisodesRoute: ApiAgentEpisodesRouteWithChildren,
  ApiPublicAgentWebhookRoute: ApiPublicAgentWebhookRoute,
  ApiAgentPromptsHistoryRoute: ApiAgentPromptsHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
